Update npm packages and fix autoloader
infinum/json-wp-post-parser pull request #9
Opened 2018-03-06 08:48 UTC by dingo-d

2018-03-06 08:51 UTC, iruzevic requested changes

2018-03-06 08:51 UTC, iruzevic commented on package.json
> +    "eslint": "^4.18.2",
we should switch to @infinum es lint config

2018-03-06 08:51 UTC, iruzevic commented on package.json
> +    "webpack": "^4.1.0",
please don't switch to 4.1 the documentation is not done and there are lot of plugins missing.

Is this working for you?

2018-03-06 08:54 UTC, dingo-d commented on package.json
> +    "webpack": "^4.1.0",
Woops, my bad, I just ran `ncu -a` and it automatically updated it. I'll revert it to v3, since I haven't tested it yet :+1:

2018-03-06 08:54 UTC, dingo-d commented on package.json
> +    "eslint": "^4.18.2",
:+1:

2018-03-06 09:26 UTC, dingo-d reviewed
I need to fix the travis builds, the autoloader is now looking at the root folder probably, and not the source.

2018-03-07 13:14 UTC, iruzevic approved these changes

2018-03-07 13:15 UTC, merged